# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) (valgrind:${{ matrix.config.valgrind }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: macOS-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'devel', valgrind: true, http-user-agent: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      # Fix suggested by
      # https://msmith.de/2020/03/12/r-cmd-check-github-actions.html
      - name: Configure git
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          install-quarto: true
          install-pandoc: true

      - uses: r-lib/actions/check-r-package@v2
        if: ${{ matrix.config.valgrind != true }}
        with:
          args: 'c("--no-manual", "--as-cran")'
          upload-snapshots: false
          upload-results: false
          check-dir: '"check"'
          error-on: '"error"'

      - name: Install valgrind
        if: ${{ matrix.config.valgrind }}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends valgrind

      - uses: r-lib/actions/check-r-package@v2
        if: ${{ matrix.config.valgrind }}
        with:
          args: 'c("--as-cran", "--use-valgrind")'

      - uses: r-lib/actions/check-r-package@v2
        if: ${{ !matrix.config.valgrind }}


      


